version: '3.8'

services:
  mosquitto-bridge:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-bridge
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto-bridge.conf:/mosquitto/config/mosquitto.conf
    restart: always
    networks:
      - mqtt-network

  mosquitto-remote:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-remote
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./config/mosquitto-remote.conf:/mosquitto/config/mosquitto.conf
    restart: always
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
